### ISSUE TITLE
About pull request #12

### ISSUE THREAD

**Issue by n0ts** [boxen/puppet-osx#44]
Hi, jfelchner's folk code is very useful for me. The pull request is #12.

I want to merge trunk this pull request, but some problems here.
1. Some manifest is now duplicate.
2. A lot of use ensure class parameter. I think that manifest class name is disable_xxx or enable_xxx etc...
3. Too large pull request.

I try to merge code this pull request, but I have some question about puppet-osx manifest.
1. Coding rule is exists?

example1: End of last paraemter is ; or , ? Like this.

```
  boxen::osx_defaults { 'Enable foo':
    user   => $::boxen_user,
    key    => 'fooKey',
    domain => 'com.apple.bar',
    value  => true,
    notify => Exec['killall SystemUIServer'];
  }
```
1. How to nameing manifest inter-class name (dock, keyboard, global...). I think that same as OS X's "System Preferences".

Thank you.

**Comment by jacobbednarz** [comment]
@n0ts are you still interested in continuing this? If so, let me know and I'll re-open.
